/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "MOSI_SDA_aliases.h"
#include "MOSI_SDA.h"
#include "SCLK_aliases.h"
#include "SCLK.h"
#include "MISO_SDO_aliases.h"
#include "MISO_SDO.h"
#include "SPI_IMU.h"
#include "SPI_IMU_PVT.h"
#include "CLOCK_PWM.h"
#include "ChipSelect_aliases.h"
#include "ChipSelect.h"
#include "UART.h"
#include "timer_clock.h"
#include "MY_TIMER_REG.h"
#include "Timer.h"
#include "UART_IntClock.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

